language: node_js
node_js:
  - 'node'
sudo: false
git:

  depth: 5

install:
  - 'npm install -g npm@latest'
  - 'npm install --only=prod'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: development
before_script:
  - "npm i -g gatsby"
script:
  - "npm run build"