language: node_js
node_js:
  - 'stable'
sudo: false

notifications:
  email:
    recipients:
      - edmundtay96@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 5

install:
  - 'yarn install  --production'
before_script:
  - "npm install -g gatsby-cli"
script:
  - "npm run build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: development
